################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_SRCS := 
ASM_UPPER_SRCS := 
C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
O_SRCS := 
SX_SRCS := 
SX_UPPER_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/arm/CMSIS_5/CMSIS/DSP/Source/BasicMathFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/BayesFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/CommonTables \
ra/arm/CMSIS_5/CMSIS/DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/ControllerFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/DistanceFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/FastMathFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/InterpolationFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/MatrixFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/QuaternionMathFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/SVMFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/StatisticsFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/SupportFunctions \
ra/arm/CMSIS_5/CMSIS/DSP/Source/TransformFunctions \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/board/ra8d1_ek \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_dmac \
ra/fsp/src/r_drw \
ra/fsp/src/r_dtc \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_mipi_dsi \
ra/fsp/src/r_mipi_phy \
ra/fsp/src/r_ospi_b \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/rm_freertos_port \
ra/tes/dave2d/src \
ra_gen \
src/Arm-2D/Acceleration/Arm/ACI/arm_2d_rgb565_aci_fvp_plugin \
src/Arm-2D/Acceleration/Arm/ACI \
src/Arm-2D/Library/Source \
src \
src/lvgl/demos/benchmark/assets \
src/lvgl/demos/benchmark \
src/lvgl/demos/flex_layout \
src/lvgl/demos/keypad_encoder \
src/lvgl/demos \
src/lvgl/demos/multilang/assets/avatars \
src/lvgl/demos/multilang/assets/emojis \
src/lvgl/demos/multilang/assets/fonts \
src/lvgl/demos/multilang/assets \
src/lvgl/demos/multilang \
src/lvgl/demos/music/assets \
src/lvgl/demos/music \
src/lvgl/demos/render/assets \
src/lvgl/demos/render \
src/lvgl/demos/scroll \
src/lvgl/demos/stress \
src/lvgl/demos/transform/assets \
src/lvgl/demos/transform \
src/lvgl/demos/vector_graphic/assets \
src/lvgl/demos/vector_graphic \
src/lvgl/demos/widgets/assets \
src/lvgl/demos/widgets \
src/lvgl/env_support/pikascript \
src/lvgl/env_support/rt-thread \
src/lvgl/env_support/rt-thread/squareline \
src/lvgl/examples/anim \
src/lvgl/examples/assets \
src/lvgl/examples/assets/emoji \
src/lvgl/examples/event \
src/lvgl/examples/get_started \
src/lvgl/examples/layouts/flex \
src/lvgl/examples/layouts/grid \
src/lvgl/examples/libs/barcode \
src/lvgl/examples/libs/bmp \
src/lvgl/examples/libs/ffmpeg \
src/lvgl/examples/libs/freetype \
src/lvgl/examples/libs/gif \
src/lvgl/examples/libs/libjpeg_turbo \
src/lvgl/examples/libs/libpng \
src/lvgl/examples/libs/lodepng \
src/lvgl/examples/libs/qrcode \
src/lvgl/examples/libs/rlottie \
src/lvgl/examples/libs/tiny_ttf \
src/lvgl/examples/libs/tjpgd \
src/lvgl/examples/others/file_explorer \
src/lvgl/examples/others/fragment \
src/lvgl/examples/others/gridnav \
src/lvgl/examples/others/ime \
src/lvgl/examples/others/imgfont \
src/lvgl/examples/others/monkey \
src/lvgl/examples/others/observer \
src/lvgl/examples/others/snapshot \
src/lvgl/examples/porting \
src/lvgl/examples/scroll \
src/lvgl/examples/styles \
src/lvgl/examples/widgets/animimg \
src/lvgl/examples/widgets/arc \
src/lvgl/examples/widgets/bar \
src/lvgl/examples/widgets/button \
src/lvgl/examples/widgets/buttonmatrix \
src/lvgl/examples/widgets/calendar \
src/lvgl/examples/widgets/canvas \
src/lvgl/examples/widgets/chart \
src/lvgl/examples/widgets/checkbox \
src/lvgl/examples/widgets/dropdown \
src/lvgl/examples/widgets/image \
src/lvgl/examples/widgets/imagebutton \
src/lvgl/examples/widgets/keyboard \
src/lvgl/examples/widgets/label \
src/lvgl/examples/widgets/led \
src/lvgl/examples/widgets/line \
src/lvgl/examples/widgets/list \
src/lvgl/examples/widgets/menu \
src/lvgl/examples/widgets/msgbox \
src/lvgl/examples/widgets/obj \
src/lvgl/examples/widgets/roller \
src/lvgl/examples/widgets/scale \
src/lvgl/examples/widgets/slider \
src/lvgl/examples/widgets/span \
src/lvgl/examples/widgets/spinbox \
src/lvgl/examples/widgets/spinner \
src/lvgl/examples/widgets/switch \
src/lvgl/examples/widgets/table \
src/lvgl/examples/widgets/tabview \
src/lvgl/examples/widgets/textarea \
src/lvgl/examples/widgets/tileview \
src/lvgl/examples/widgets/win \
src/lvgl/src/core \
src/lvgl/src/display \
src/lvgl/src/draw \
src/lvgl/src/draw/nxp/pxp \
src/lvgl/src/draw/nxp/vglite \
src/lvgl/src/draw/renesas/dave2d \
src/lvgl/src/draw/sdl \
src/lvgl/src/draw/sw/blend/helium \
src/lvgl/src/draw/sw/blend \
src/lvgl/src/draw/sw/blend/neon \
src/lvgl/src/draw/sw \
src/lvgl/src/draw/vg_lite \
src/lvgl/src/drivers/display/drm \
src/lvgl/src/drivers/display/fb \
src/lvgl/src/drivers/display/ili9341 \
src/lvgl/src/drivers/display/lcd \
src/lvgl/src/drivers/display/st7735 \
src/lvgl/src/drivers/display/st7789 \
src/lvgl/src/drivers/display/st7796 \
src/lvgl/src/drivers/display/tft_espi \
src/lvgl/src/drivers/evdev \
src/lvgl/src/drivers/libinput \
src/lvgl/src/drivers/nuttx \
src/lvgl/src/drivers/sdl \
src/lvgl/src/drivers/windows \
src/lvgl/src/drivers/x11 \
src/lvgl/src/font \
src/lvgl/src/indev \
src/lvgl/src/layouts/flex \
src/lvgl/src/layouts/grid \
src/lvgl/src/layouts \
src/lvgl/src/libs/barcode \
src/lvgl/src/libs/bin_decoder \
src/lvgl/src/libs/bmp \
src/lvgl/src/libs/ffmpeg \
src/lvgl/src/libs/freetype \
src/lvgl/src/libs/fsdrv \
src/lvgl/src/libs/gif \
src/lvgl/src/libs/libjpeg_turbo \
src/lvgl/src/libs/libpng \
src/lvgl/src/libs/lodepng \
src/lvgl/src/libs/lz4 \
src/lvgl/src/libs/qrcode \
src/lvgl/src/libs/rle \
src/lvgl/src/libs/rlottie \
src/lvgl/src/libs/thorvg \
src/lvgl/src/libs/tiny_ttf \
src/lvgl/src/libs/tjpgd \
src/lvgl/src \
src/lvgl/src/misc/cache \
src/lvgl/src/misc \
src/lvgl/src/osal \
src/lvgl/src/others/file_explorer \
src/lvgl/src/others/fragment \
src/lvgl/src/others/gridnav \
src/lvgl/src/others/ime \
src/lvgl/src/others/imgfont \
src/lvgl/src/others/monkey \
src/lvgl/src/others/observer \
src/lvgl/src/others/snapshot \
src/lvgl/src/others/sysmon \
src/lvgl/src/others/vg_lite_tvg \
src/lvgl/src/stdlib/builtin \
src/lvgl/src/stdlib/clib \
src/lvgl/src/stdlib \
src/lvgl/src/stdlib/micropython \
src/lvgl/src/stdlib/rtthread \
src/lvgl/src/themes/default \
src/lvgl/src/themes \
src/lvgl/src/themes/mono \
src/lvgl/src/themes/simple \
src/lvgl/src/tick \
src/lvgl/src/widgets/animimage \
src/lvgl/src/widgets/arc \
src/lvgl/src/widgets/bar \
src/lvgl/src/widgets/button \
src/lvgl/src/widgets/buttonmatrix \
src/lvgl/src/widgets/calendar \
src/lvgl/src/widgets/canvas \
src/lvgl/src/widgets/chart \
src/lvgl/src/widgets/checkbox \
src/lvgl/src/widgets/dropdown \
src/lvgl/src/widgets/image \
src/lvgl/src/widgets/imagebutton \
src/lvgl/src/widgets/keyboard \
src/lvgl/src/widgets/label \
src/lvgl/src/widgets/led \
src/lvgl/src/widgets/line \
src/lvgl/src/widgets/list \
src/lvgl/src/widgets/menu \
src/lvgl/src/widgets/msgbox \
src/lvgl/src/widgets/objx_templ \
src/lvgl/src/widgets/roller \
src/lvgl/src/widgets/scale \
src/lvgl/src/widgets/slider \
src/lvgl/src/widgets/span \
src/lvgl/src/widgets/spinbox \
src/lvgl/src/widgets/spinner \
src/lvgl/src/widgets/switch \
src/lvgl/src/widgets/table \
src/lvgl/src/widgets/tabview \
src/lvgl/src/widgets/textarea \
src/lvgl/src/widgets/tileview \
src/lvgl/src/widgets/win \
src/port \

